import { createSlice } from '@reduxjs/toolkit';
import { formatDateFromString } from '../../../utils/utilityFunctions';

const initialState = {
  inventoryTypes: [
    {
      id: 1,
      business_ID: 100000,
      name: '食品',
      description:
        'おつまみ、主食、缶詰、生鮮食品など、さまざまな種類の食用品。',
    },
    {
      id: 2,
      business_ID: 100000,
      name: '野菜',
      description: '葉物野菜、根菜類、季節の野菜など、新鮮な野菜と冷凍野菜。',
    },
    {
      id: 3,
      business_ID: 100000,
      name: '果物',
      description: '季節の果物、冷凍果物、果物の缶詰など。',
    },
    {
      id: 4,
      business_ID: 100000,
      name: '肉',
      description: '牛肉、豚肉、鶏肉、その他の肉類。',
    },
    {
      id: 5,
      business_ID: 100000,
      name: '魚',
      description: '魚介類、海藻類、その他の魚介類。',
    },
    {
      id: 6,
      business_ID: 100000,
      name: '調味料',
      description: '醤油、味醂、酢、塩、砂糖、胡椒、その他の調味料。',
    },
    {
      id: 7,
      business_ID: 100000,
      name: 'アルコール',
      description:
        'ビール、ワイン、ウイスキー、焼酎、日本酒、その他のアルコール飲料。',
    },
    {
      id: 8,
      business_ID: 100000,
      name: '麺',
      description: 'ラーメン麺、そば麺、うどん麺、その他の麺類。',
    },
    {
      id: 9,
      business_ID: 100000,
      name: '飲料',
      description: '水、お茶、ジュース、ソーダ、その他の飲料。',
    },
    {
      id: 10,
      business_ID: 100000,
      name: 'その他',
      description: 'その他の食材。',
    },
  ],
  inventory: [
    {
      id: 1,
      business_ID: 100000,
      inventoryType: '食品',
      itemName: '卵',
      stockQuantity: 100,
      volumePerItem: 400.0,
      volumeUnit: 'g',
      costPrice: 200.0,
      supplierDetails: '株式会社卵最高',
      lastOrdered: formatDateFromString('2023年12月20日'),
    },
    {
      id: 2,
      business_ID: 100000,
      inventoryType: '調味料',
      itemName: '砂糖',
      stockQuantity: 5,
      volumePerItem: 0.8,
      volumeUnit: 'kg',
      costPrice: 250.0,
      supplierDetails: '株式会社砂糖ラバーズ',
      lastOrdered: formatDateFromString('2023年05月05日'),
    },
    {
      id: 3,
      business_ID: 100000,
      inventoryType: '調味料',
      itemName: '醤油',
      stockQuantity: 10,
      volumePerItem: 500,
      volumeUnit: 'ml',
      costPrice: 285.0,
      supplierDetails: '株式会社醤油マスター',
      lastOrdered: formatDateFromString('2023年08月29日'),
    },
    {
      id: 4,
      business_ID: 100000,
      inventoryType: '調味料',
      itemName: '味醂',
      stockQuantity: 5,
      volumePerItem: 500,
      volumeUnit: 'ml',
      costPrice: 550.0,
      supplierDetails: '株式会社味醂王様',
      lastOrdered: formatDateFromString('2023年12月29日'),
    },
    {
      id: 5,
      business_ID: 100000,
      inventoryType: '調味料',
      itemName: '塩',
      stockQuantity: 20,
      volumePerItem: 1,
      volumeUnit: 'kg',
      costPrice: 140.0,
      supplierDetails: '株式会社塩ベスト',
      lastOrdered: formatDateFromString('2023年10月14日'),
    },
    {
      id: 6,
      business_ID: 100000,
      inventoryType: '肉',
      itemName: '豚骨',
      stockQuantity: 25,
      volumePerItem: 12.5,
      volumeUnit: 'kg',
      costPrice: 10000.0,
      supplierDetails: '田中家族ファーム',
      lastOrdered: formatDateFromString('2023年10月12日'),
    },
    {
      id: 7,
      business_ID: 100000,
      inventoryType: '肉',
      itemName: '豚バラ',
      stockQuantity: 40,
      volumePerItem: 12.5,
      volumeUnit: 'kg',
      costPrice: 14000.0,
      supplierDetails: '田中家族ファーム',
      lastOrdered: formatDateFromString('2023年10月12日'),
    },
    {
      id: 8,
      business_ID: 100000,
      inventoryType: '麺',
      itemName: 'ラーメン麺',
      stockQuantity: 50,
      volumePerItem: 4.5,
      volumeUnit: 'kg',
      costPrice: 1500.0,
      supplierDetails: '株式会社ラーメン麺',
      lastOrdered: formatDateFromString('2023年12月10日'),
    },
    {
      id: 9,
      business_ID: 100000,
      inventoryType: '野菜',
      itemName: 'ネギ',
      stockQuantity: 100,
      volumePerItem: 1,
      volumeUnit: 'kg',
      costPrice: 400.0,
      supplierDetails: '田中家族ファーム',
      lastOrdered: formatDateFromString('2023年11月15日'),
    },
    {
      id: 10,
      business_ID: 100000,
      inventoryType: '野菜',
      itemName: '大蒜',
      stockQuantity: 100,
      volumePerItem: 1,
      volumeUnit: 'kg',
      costPrice: 500.0,
      supplierDetails: '田中家族ファーム',
      lastOrdered: formatDateFromString('2023年11月15日'),
    },
    {
      id: 11,
      business_ID: 100000,
      inventoryType: '野菜',
      itemName: '生姜',
      stockQuantity: 100,
      volumePerItem: 1,
      volumeUnit: 'kg',
      costPrice: 600.0,
      supplierDetails: '田中家族ファーム',
      lastOrdered: formatDateFromString('2023年11月30日'),
    },
    {
      id: 12,
      business_ID: 100000,
      inventoryType: '調味料',
      itemName: 'ごま油',
      stockQuantity: 100,
      volumePerItem: 750,
      volumeUnit: 'ml',
      costPrice: 800.0,
      supplierDetails: '岩見商店',
      lastOrdered: formatDateFromString('2023年11月30日'),
    },
    {
      id: 13,
      business_ID: 100000,
      inventoryType: '調味料',
      itemName: '海苔',
      stockQuantity: 50,
      volumePerItem: 20,
      volumeUnit: 'g',
      costPrice: 400.0,
      supplierDetails: '岩見商店',
      lastOrdered: formatDateFromString('2024年1月01日'),
    },
    {
      id: 14,
      business_ID: 100000,
      inventoryType: '調味料',
      itemName: '黒胡椒',
      stockQuantity: 100,
      volumePerItem: 400,
      volumeUnit: 'g',
      costPrice: 600.0,
      supplierDetails: '岩見商店',
      lastOrdered: formatDateFromString('2023年11月30日'),
    },
    {
      id: 15,
      business_ID: 100000,
      inventoryType: '野菜',
      itemName: 'もやし',
      stockQuantity: 100,
      volumePerItem: 120,
      volumeUnit: 'g',
      costPrice: 300.0,
      supplierDetails: '田中家族ファーム',
      lastOrdered: formatDateFromString('2023年12月10日'),
    },
    {
      id: 16,
      business_ID: 100000,
      inventoryType: '飲料',
      itemName: 'コーラ',
      stockQuantity: 100,
      volumePerItem: 2,
      volumeUnit: 'L',
      costPrice: 200.0,
      supplierDetails: 'ファマリー・マート',
      lastOrdered: formatDateFromString('2023年12月10日'),
    },
    {
      id: 17,
      business_ID: 100000,
      inventoryType: 'アルコール',
      itemName: 'ウイスキー',
      stockQuantity: 20,
      volumePerItem: 750,
      volumeUnit: 'ml',
      costPrice: 2750.0,
      supplierDetails: '渡辺お酒屋',
      lastOrdered: formatDateFromString('2023年12月10日'),
    },
    {
      id: 18,
      business_ID: 100000,
      inventoryType: '果物',
      itemName: 'レモン',
      stockQuantity: 150,
      volumePerItem: 100,
      volumeUnit: 'g',
      costPrice: 100.0,
      supplierDetails: '田中家族ファーム',
      lastOrdered: formatDateFromString('2023年12月10日'),
    },
    {
      id: 19,
      business_ID: 100000,
      inventoryType: 'アルコール',
      itemName: '焼酎',
      stockQuantity: 20,
      volumePerItem: 750,
      volumeUnit: 'ml',
      costPrice: 2300.0,
      supplierDetails: '渡辺お酒屋',
      lastOrdered: formatDateFromString('2023年12月10日'),
    },
    {
      id: 20,
      business_ID: 100000,
      inventoryType: '飲料',
      itemName: 'ソーダ水',
      stockQuantity: 100,
      volumePerItem: 1,
      volumeUnit: 'L',
      costPrice: 120.0,
      supplierDetails: 'ファマリー・マート',
      lastOrdered: formatDateFromString('2023年12月10日'),
    },
    {
      id: 21,
      business_ID: 100000,
      inventoryType: '飲料',
      itemName: 'ザクロジュース',
      stockQuantity: 100,
      volumePerItem: 1,
      volumeUnit: 'L',
      costPrice: 250.0,
      supplierDetails: 'ファマリー・マート',
      lastOrdered: formatDateFromString('2024年01月10日'),
    },
  ],
};

const inventorySlice = createSlice({
  name: 'inventory',
  initialState,
  reducers: {
    addInventoryType: (state, action) => {
      const newInventoryType = { ...action.payload };
      state.inventoryTypes.push(newInventoryType);
    },
    updateInventoryType: (state, action) => {
      state.inventoryTypes = action.payload;
    },
    addInventory: (state, action) => {
      const newInventory = { ...action.payload };
      state.inventory.push(newInventory);
    },
    updateInventory: (state, action) => {
      state.inventory = action.payload;
    },
  },
});

export const selectAllinventory = state => state.inventory.inventory;
export const selectAllinventoryTypes = state => state.inventory.inventoryTypes;

export const {
  addInventory,
  updateInventory,
  addInventoryType,
  updateInventoryType,
} = inventorySlice.actions;
export default inventorySlice.reducer;
